### ISSUE TITLE
Tambahkan Informasi How to Install dan Server Requirement pada README.md 

### ISSUE THREAD

**Issue by nafiesl** [rizalihwan/point-of-sale#1]
Halo mas @rizalihwan, kalau boleh saya kasih masukan untuk project ini, agar ditambahkan informasi:
1. Cara install project
2. Server requirement (seperti minimal versi php, atau versi databse)

Biasanya 2 dokumentasi di atas dituliskan pada README.md. Informasi ini akan mempermudah orang lain yang ingin explore project ini.

**Comment by rizalihwan** [comment]
Done Mas.

**Comment by rizalihwan** [comment]
> Halo mas @rizalihwan, kalau boleh saya kasih masukan untuk project ini, agar ditambahkan informasi:
> 
>     1. Cara install project
> 
>     2. Server requirement (seperti minimal versi php, atau versi databse)
> 
> 
> Biasanya 2 dokumentasi di atas dituliskan pada README.md. Informasi ini akan mempermudah orang lain yang ingin explore project ini.

Done Mas.
